"""宿主适配器协议。共享内核不认识任何宿主 ORM 模型。"""

from __future__ import annotations

import uuid
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, Protocol

from enterprise_platform.easyauth.types import DirectorySnapshotMeta, DirectoryUserRecord
from enterprise_platform.schemas import (
    AuthorizationCatalogItem,
    AuthorizationConnectionResult,
    AuthorizationSettings,
    AuthorizationSettingsUpdate,
    AuthorizationSnapshot,
    AuthorizationStatus,
    ConnectionTestResult,
    CurrentUser,
    DescriptorKeyCreateRequest,
    DescriptorKeyCreateResponse,
    DescriptorKeyResponse,
    DescriptorKeyUpdateRequest,
    DirectorySettings,
    DirectorySettingsUpdate,
    DirectorySyncResult,
    EasyAuthSettingsUpdate,
    EasyAuthStatus,
    FooterSettings,
    IdentityDiscoveryResponse,
    MyGrantResponse,
    NotificationPage,
    OidcSettings,
    OidcSettingsUpdate,
    PasskeySummary,
    PermissionRequestUrlUpdate,
    UpstreamHealthItem,
)


@dataclass(frozen=True)
class LocalAccount:
    id: str
    name: str
    email: str | None
    avatar_url: str | None
    ui_locale: str
    active: bool
    is_local_superuser: bool
    must_change_password: bool
    totp_enabled: bool
    has_passkey: bool


@dataclass(frozen=True)
class PasskeyChallenge:
    options: dict[str, Any]
    state_token: str


class AccountPort(Protocol):
    def authenticate_password(self, username: str, password: str) -> LocalAccount | None: ...
    def verify_totp(self, account_id: str, code: str) -> bool: ...
    def issue_session(self, account_id: str) -> str: ...
    def current_user(self) -> CurrentUser: ...
    def revoke_sessions(self, account_id: str) -> None: ...
    def change_password(self, account_id: str, current_password: str, new_password: str) -> bool: ...
    def totp_status(self, account_id: str) -> bool: ...
    def totp_begin(self, account_id: str) -> tuple[str, str]: ...
    def totp_confirm(self, account_id: str, code: str) -> bool: ...
    def totp_disable(self, account_id: str, password: str, code: str) -> bool: ...
    def list_passkeys(self, account_id: str) -> list[PasskeySummary]: ...
    def begin_passkey_login(self, account_id: str) -> PasskeyChallenge: ...
    def complete_passkey_login(self, account_id: str, state_token: str, credential: dict[str, Any]) -> bool: ...
    def begin_passkey_registration(self, account_id: str) -> PasskeyChallenge: ...
    def complete_passkey_registration(
        self, account_id: str, state_token: str, credential: dict[str, Any], name: str
    ) -> PasskeySummary: ...
    def delete_passkey(self, account_id: str, passkey_id: str) -> bool: ...


class FooterPort(Protocol):
    def get_footer(self) -> FooterSettings: ...
    def save_footer(self, footer: FooterSettings, *, actor_id: str) -> FooterSettings: ...


class NotificationPort(Protocol):
    def list_notifications(self, user_id: str, *, cursor: str | None, limit: int) -> NotificationPage: ...
    def mark_read(self, user_id: str, notification_id: str, *, read_at: datetime) -> bool: ...
    def mark_all_read(self, user_id: str, *, read_at: datetime) -> int: ...


class IntegrationPort(Protocol):
    def get_oidc_settings(self) -> OidcSettings: ...
    def save_oidc_settings(self, payload: OidcSettingsUpdate, *, actor_id: str) -> OidcSettings: ...
    def test_oidc(self) -> ConnectionTestResult: ...
    def discover_oidc(self, issuer: str | None) -> IdentityDiscoveryResponse: ...
    def get_easyauth_status(self) -> EasyAuthStatus: ...
    def save_easyauth_settings(self, payload: EasyAuthSettingsUpdate, *, actor_id: str) -> EasyAuthStatus: ...
    def save_permission_request_url(self, payload: PermissionRequestUrlUpdate, *, actor_id: str) -> EasyAuthStatus: ...
    def test_easyauth(self) -> ConnectionTestResult: ...
    def get_easyauth_webhook_secret(self) -> str: ...


class DirectoryProjectionPort(Protocol):
    """宿主用户表投影。仅在权威快照下由 ``run_directory_sync`` 调用写入方法。"""

    def begin(self, snapshot: DirectorySnapshotMeta) -> None: ...
    def upsert_user(self, user: DirectoryUserRecord) -> Literal["created", "updated", "unchanged"]: ...
    def deactivate_missing(self, seen_user_refs: frozenset[str]) -> int: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class DirectoryPort(Protocol):
    def get_directory_settings(self) -> DirectorySettings: ...
    def save_directory_settings(self, payload: DirectorySettingsUpdate, *, actor_id: str) -> DirectorySettings: ...
    def test_directory(self) -> ConnectionTestResult: ...
    def sync_directory(self, *, actor_id: str) -> DirectorySyncResult: ...


class UpstreamHealthPort(Protocol):
    def latest(self) -> list[UpstreamHealthItem]: ...
    def run_checks(self, *, actor_id: str) -> list[UpstreamHealthItem]: ...


class AuthorizationOperationsPort(Protocol):
    """共享登录与权限 UI 所需的完整授权运维边界。"""

    def status(self) -> AuthorizationStatus: ...
    def connection_test(self, *, actor_id: str) -> AuthorizationConnectionResult: ...
    def get_settings(self) -> AuthorizationSettings: ...
    def save_settings(self, payload: AuthorizationSettingsUpdate, *, actor_id: str) -> AuthorizationSettings: ...
    def list_catalog(self, *, search: str | None, active: bool | None) -> list[AuthorizationCatalogItem]: ...
    def list_snapshots(
        self, *, search: str | None, offset: int, limit: int, sort: str
    ) -> tuple[list[AuthorizationSnapshot], int]: ...
    def refresh_snapshot(self, user_id: uuid.UUID, *, actor_id: str) -> AuthorizationSnapshot: ...
    def refresh_snapshot_for_external_user(self, external_user_id: str, expected_snapshot_version: str) -> None: ...
    def invalidate_app_snapshots(self, app_key: str, catalog_version: int) -> None: ...
    def manifest(self, *, schema_version: int | None, actor_id: str) -> dict[str, Any]: ...
    def my_grants(self, *, actor_id: str) -> list[MyGrantResponse]: ...
    def list_descriptor_keys(self) -> list[DescriptorKeyResponse]: ...
    def create_descriptor_key(
        self, payload: DescriptorKeyCreateRequest, *, actor_id: str
    ) -> DescriptorKeyCreateResponse: ...
    def update_descriptor_key(
        self, key_id: uuid.UUID, payload: DescriptorKeyUpdateRequest, *, actor_id: str
    ) -> DescriptorKeyResponse: ...
    def delete_descriptor_key(self, key_id: uuid.UUID, *, actor_id: str) -> None: ...


PermissionCheck = Callable[[str], None]
