import type { EnterpriseLocalAccountsLabels } from "@easy-enterprise/ui/enterprise-local-accounts";
import type { EnterpriseCatalogLocale } from "@easy-enterprise/ui/enterprise";

export function localAccountsLabels(locale: EnterpriseCatalogLocale): EnterpriseLocalAccountsLabels {
  if (locale === "en") {
    return {
      title: "Local accounts",
      description: "Create and manage framework-local accounts and their permission grants.",
      permissionDenied: "This account cannot view local accounts.",
      loading: "Loading",
      loadFailed: "Failed to load local accounts",
      empty: "No local accounts",
      retry: "Retry",
      searchPlaceholder: "Search username or email",
      search: "Search",
      create: "Create account",
      refresh: "Refresh",
      username: "Username",
      email: "Email",
      password: "Password",
      status: "Status",
      permissions: "Permissions",
      actions: "Actions",
      active: "Active",
      inactive: "Disabled",
      admin: "Admin",
      totpEnabled: "2FA",
      mustChangePassword: "Must change password",
      expired: "Expired",
      permissionCount: (count) => `${count}`,
      createTitle: "Create local account",
      editTitle: "Edit local account",
      save: "Save",
      saving: "Saving…",
      cancel: "Cancel",
      close: "Close",
      generatePassword: "Generate",
      copyPassword: "Copy",
      passwordCopied: "Password copied",
      copyFailed: "Could not copy password",
      mustChangePasswordHint: "Require a password change on next sign-in.",
      isAdmin: "Administrator",
      isAdminHint: "Administrators hold all permissions; grants are not stored.",
      permissionPickerTitle: "Permission grants",
      permissionPickerAdminNote: "Admin accounts hold all permissions. Individual grants cannot be edited.",
      permissionPickerEmpty: "No permissions in the active catalog.",
      permissionPickerBaselineHint: "Baseline self-service permission, granted to every local account",
      permissionCatalogLoadFailed: "Failed to load the permission catalog",
      permissionNotGrantable: "Not grantable to local users",
      permissionHighRisk: "High risk",
      scopeLabel: "Scope",
      copyGrantsFrom: "Copy grants from existing account",
      copyGrantsFromPlaceholder: "Select an account…",
      copyGrantsFromSuccess: "Grants imported",
      copyGrantsFromFailed: "Failed to import grants",
      grantsConflict: "Grants were modified by someone else. Reload and try again.",
      expiresAt: "Expires at",
      expiresAtHint: "Leave empty for a permanent account. Superadmin accounts cannot expire.",
      expiresAtPermanent: "Permanent",
      clearExpiry: "Clear expiry",
      passwordReceiptTitle: "One-time password",
      passwordReceiptHint:
        "Copy this password now and hand it to the account owner. The application cannot read the system clipboard after you leave this dialog.",
      passwordReceiptConfirm: "I have copied the password",
      createSuccess: "Local account created",
      createFailed: "Failed to create local account",
      updateSuccess: "Account updated",
      updateFailed: "Failed to update account",
      delete: "Delete account",
      deleteConfirm: "Delete this local account permanently?",
      deleteSuccess: "Local account deleted",
      deleteFailed: "Failed to delete local account",
      activate: "Activate",
      deactivate: "Deactivate",
      statusUpdateSuccess: "Account status updated",
      statusUpdateFailed: "Failed to update account status",
      resetPasswordTitle: "Reset password",
      resetPassword: "Reset password",
      resetPasswordSuccess: "Password reset",
      resetPasswordFailed: "Failed to reset password",
      disableTotp: "Disable 2FA",
      disableTotpConfirm: "Disable two-factor authentication for this account?",
      disableTotpSuccess: "Two-factor authentication disabled",
      disableTotpFailed: "Failed to disable two-factor authentication",
      promoteAdmin: "Promote to admin",
      demoteAdmin: "Demote admin",
      adminUpdateSuccess: "Administrator status updated",
      adminUpdateFailed: "Failed to update administrator status",
      savePermissions: "Save permissions",
      permissionsSuccess: "Permissions updated",
      permissionsFailed: "Failed to update permissions",
      usernameRequired: "Username is required",
      passwordRequired: "Password is required",
      profileSection: "Profile",
      dangerSection: "Danger zone",
      open: "Open",
      notAvailable: "—",
    };
  }

  return {
    title: "本地账户",
    description: "创建与管理框架本地账户及其权限授予。",
    permissionDenied: "当前账号没有查看本地账户的权限。",
    loading: "正在加载",
    loadFailed: "本地账户加载失败",
    empty: "暂无本地账户",
    retry: "重试",
    searchPlaceholder: "搜索用户名或邮箱",
    search: "搜索",
    create: "创建账户",
    refresh: "刷新",
    username: "用户名",
    email: "邮箱",
    password: "密码",
    status: "状态",
    permissions: "权限",
    actions: "操作",
    active: "启用",
    inactive: "已停用",
    admin: "管理员",
    totpEnabled: "二次验证",
    mustChangePassword: "须改密",
    expired: "已过期",
    permissionCount: (count) => `${count}`,
    createTitle: "创建本地账户",
    editTitle: "编辑本地账户",
    save: "保存",
    saving: "正在保存…",
    cancel: "取消",
    close: "关闭",
    generatePassword: "随机生成",
    copyPassword: "复制",
    passwordCopied: "密码已复制",
    copyFailed: "复制密码失败",
    mustChangePasswordHint: "下次登录时强制修改密码。",
    isAdmin: "管理员",
    isAdminHint: "管理员拥有全部权限，不单独存储授权列表。",
    permissionPickerTitle: "权限授予",
    permissionPickerAdminNote: "管理员账户拥有全部权限，无法编辑单项授权。",
    permissionPickerEmpty: "当前权限目录为空。",
    permissionPickerBaselineHint: "自助基线权限，所有本地账户默认拥有",
    permissionCatalogLoadFailed: "权限目录加载失败",
    permissionNotGrantable: "不可授予本地用户",
    permissionHighRisk: "高风险",
    scopeLabel: "作用域",
    copyGrantsFrom: "从已有账户复制授权",
    copyGrantsFromPlaceholder: "选择账户…",
    copyGrantsFromSuccess: "授权已导入",
    copyGrantsFromFailed: "导入授权失败",
    grantsConflict: "授权已被他人修改，请刷新后重试。",
    expiresAt: "有效期",
    expiresAtHint: "留空表示永久有效。超级管理员账户不可设置有效期。",
    expiresAtPermanent: "永久",
    clearExpiry: "清除有效期",
    passwordReceiptTitle: "一次性密码交接",
    passwordReceiptHint: "请立即复制并交给账户使用者。关闭后应用无法再读取系统剪贴板。",
    passwordReceiptConfirm: "我已复制密码",
    createSuccess: "本地账户已创建",
    createFailed: "创建本地账户失败",
    updateSuccess: "账户已更新",
    updateFailed: "更新账户失败",
    delete: "删除账户",
    deleteConfirm: "确定永久删除此本地账户？",
    deleteSuccess: "本地账户已删除",
    deleteFailed: "删除本地账户失败",
    activate: "启用",
    deactivate: "停用",
    statusUpdateSuccess: "账户状态已更新",
    statusUpdateFailed: "更新账户状态失败",
    resetPasswordTitle: "重置密码",
    resetPassword: "重置密码",
    resetPasswordSuccess: "密码已重置",
    resetPasswordFailed: "重置密码失败",
    disableTotp: "解除二次验证",
    disableTotpConfirm: "确定解除此账户的二次验证？",
    disableTotpSuccess: "二次验证已解除",
    disableTotpFailed: "解除二次验证失败",
    promoteAdmin: "升为超管",
    demoteAdmin: "取消超管",
    adminUpdateSuccess: "管理员状态已更新",
    adminUpdateFailed: "更新管理员状态失败",
    savePermissions: "保存权限",
    permissionsSuccess: "权限已更新",
    permissionsFailed: "更新权限失败",
    usernameRequired: "请输入用户名",
    passwordRequired: "请输入密码",
    profileSection: "资料",
    dangerSection: "危险操作",
    open: "打开",
    notAvailable: "—",
  };
}
